describe('Test for the classifier index page', () => {
    before(() => {
      cy.login('m5BzIaViiTRrMnHwzjAHU3FwcRm2').then(user => {
        console.log('user')
        console.log(user)
      })
      cy.visit('/')
    
    })
    it('loads the details page when the details button is clicked',()=>{
        cy.visit('/admin')
        cy.wait(5000)
        cy.get('#detaisBtn').click({force: true})
        cy.wait(25000)
        cy.contains('User submitted image(s)')
        cy.contains('User Reported Data')
        cy.contains('Household')
        cy.contains('Shopping')
        cy.contains('Food')
        cy.contains('Progress')
    })
    it('It will load the hosehold section data when the hosehold section is clicked',()=>{
        cy.visit('/admin')
        cy.wait(5000)
        cy.get('#detaisBtn').click({force: true})
        cy.wait(25000)
        cy.get('#householdSection').click({force: true})
        cy.contains('Electricity')
    })
    it('It will pass to the next record when the valid button is clicked on the household section',()=>{
        cy.visit('/admin')
        cy.wait(5000)
        cy.get('#detaisBtn').click({force: true})
        cy.wait(25000)
        cy.get('#householdSection').click({force: true})
        cy.wait(5000)
        cy.get('#validBtn').click({force: true})
        cy.wait(5000)
        cy.contains('Natural gas')
    })
    it('It will provide an input for the user to enter the new value when the user clicks the invalid button',()=>{
        cy.visit('/admin')
        cy.wait(5000)
        cy.get('#detaisBtn').click({force: true})
        cy.wait(25000)
        cy.get('#householdSection').click({force: true})
        cy.wait(5000)
        cy.get('#inValidBtn').click({force: true})
        cy.wait(5000)
        cy.contains('Please add the correct value from the photo')
    })
    it('It will load the shopping section data when the shopping tab is clicked',()=>{
        cy.visit('/admin')
        cy.wait(5000)
        cy.get('#detaisBtn').click({force: true})
        cy.wait(25000)
        cy.get('#shoppingSection').click({force: true})
        cy.wait(5000)
        cy.contains('Paper')
        cy.contains('Plastic')
        cy.contains('Textile')
        cy.contains('Pharmaceuticals')
    })
    it('It will provide an input for the user to enter the new value when the user clicks the invalid button',()=>{
      cy.visit('/admin')
      cy.wait(5000)
      cy.get('#detaisBtn').click({force: true})
      cy.wait(25000)
      cy.get('#shoppingSection').click({force: true})
      cy.wait(5000)
      cy.get('#inValidBtn').click({force: true})
      cy.wait(5000)
      cy.contains('Please add the correct value(s) from the photo')
  })
    })